<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Thanks for register</title>
</head>
<body>
<h1> Подтверждение почты</h1>
<img src="https://kpfu.ru//portal/docs/F_1839660337/IMG_20260227_195609_685.png" alt="">
<h2><a href="http://localhost:8080/confirm/${confirm_code}">Подтвержедние почты</a> </h2>
</body>
</html>